Document: dfterm2
Title: Debian dfterm2 Manual
Author: <insert document author here>
Abstract: This manual describes what dfterm2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dfterm2/dfterm2.sgml.gz

Format: postscript
Files: /usr/share/doc/dfterm2/dfterm2.ps.gz

Format: text
Files: /usr/share/doc/dfterm2/dfterm2.text.gz

Format: HTML
Index: /usr/share/doc/dfterm2/html/index.html
Files: /usr/share/doc/dfterm2/html/*.html
