#!/bin/sh

TMP_USER=$(logname)

mkdir $HOME/.dfterm2

cat > $HOME/.dfterm2/dfterm2.conf << EOF
database = "$HOME/.dfterm2/dfterm2_database.sqlite3"
logfile = "$HOME/.dfterm2/dfterm2.log"

addresses = {
   { name               = "DF 31.25",
     size_address       = 0x0073507C,
     screendata_address = 0x00734D1C,
     checksum           = 0xFBFF0FC9,
     method             = "PackedVarying" }
 }
EOF

chown -R $TMP_USER:$TMP_USER $HOME/.dfterm2
chmod -R 0700 $HOME/.dfterm2
